# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "cantrip-timer-component"
version = "0.1.0"
edition = "2021"

[features]
CONFIG_PLAT_BCM2837 = []
CONFIG_PLAT_SPARROW = []

[dependencies]
cantrip-os-common = { path = "../../cantrip-os-common" }
cantrip-timer-interface = { path = "../cantrip-timer-interface" }
cantrip-timer-service = { path = "../cantrip-timer-service" }
log = { version = "0.4", features = ["release_max_level_info"] }

[lib]
name = "cantrip_timer_component"
path = "src/run.rs"
crate-type = ["staticlib"]
