cargo-features = ["edition2021"]

[package]
name = "cantrip-security-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
postcard = { version = "0.7", features = ["alloc"], default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde-big-array = "0.3"
