# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "cantrip-proc-manager"
version = "0.1.0"
description = "Cantrip OS ProcessManager services"
edition = "2021"
build = "build.rs"

[build-dependencies]
sel4-config = { path = "../../cantrip-os-common/src/sel4-config" }

[features]
default = []
CONFIG_CAPDL_LOADER_CC_REGISTERS = []
CONFIG_CAPDL_LOADER_WRITEABLE_PAGES = []
CONFIG_DEBUG_BUILD = []
CONFIG_PRINTING = []
CONFIG_KERNEL_MCS = []
CONFIG_SMP_SUPPORT = []

[dependencies]
cstr_core = "0.2.3"
hashbrown = { version = "0.11", features = ["ahash-compile-time-rng"] }
cantrip-io = { path = "../../DebugConsole/cantrip-io" }
cantrip-proc-interface = { path = "../cantrip-proc-interface" }
cantrip-memory-interface = { path = "../../MemoryManager/cantrip-memory-interface" }
cantrip-os-common = { path = "../../cantrip-os-common" }
cantrip-security-interface = { path = "../../SecurityCoordinator/cantrip-security-interface" }
log = "0.4"
smallstr = "0.2"
spin = "0.9"
static_assertions = "1.1"
