[package]
name = "allocator"
version = "0.1.0"
authors = ["Sam Leffler <sleffler@google.com>"]
edition = "2021"

[dependencies]
linked_list_allocator = { version = "0.9", default-features = false, features = ["const_mut_refs"] }
spin = "0.9"
